EventRSVP/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventRSVP.Models;

namespace EventRSVP.Controllers
{
    public class EventController : Controller
    {
        private RSVPModelContainer db = new RSVPModelContainer();

        //
        // GET: /Event/

        public ActionResult Login()
        {
            var loggedin = Session["LoggedIn"];
            if (loggedin != null)
            {
                if (loggedin.ToString() == System.Configuration.ConfigurationManager.AppSettings["EventsPassword"])
                {
                    return View("Index", db.Events.ToList());
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.PasswordLogin == System.Configuration.ConfigurationManager.AppSettings["EventsPassword"])
                {
                    Session["LoggedIn"] = model.PasswordLogin;
                    return View("Index", db.Events.ToList());
                }
            }
            ModelState.AddModelError("PasswordLogin", "Incorrect Password");
            return View();
        }

        //
        // GET: /Event/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Event/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventModel eventt)
        {
            if (ModelState.IsValid)
            {
                Event e = new Event();
                e.Title = eventt.Title;
                e.CompanyEmail = eventt.CompanyEmail;
                e.CompanyName = eventt.CompanyName;
                e.Password = eventt.Password;
                
                db.Events.Add(e);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(eventt);
        }

        //
        // GET: /Event/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Event eventt = db.Events.Find(id);
            if (eventt == null)
            {
                return HttpNotFound();
            }
            return View(eventt);
        }

        //
        // POST: /Event/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event eventt)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Login");
            }
            return View(eventt);
        }

        //
        // GET: /Event/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Event eventt = db.Events.Find(id);
            if (eventt != null)
            {
                eventt.Registrations.Clear();

                var registrationsByEvent = db.Registrations.Include(r => r.Event).Where(r => r.EventId == id);
                foreach (Registration r in registrationsByEvent)
                {
                    db.Registrations.Remove(r);
                }

                db.Events.Remove(eventt);
                db.SaveChanges();
            }
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EventRSVP/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventRSVP.Models;

namespace EventRSVP.Controllers
{
    public class RegistrationController : Controller
    {
        private RSVPModelContainer db = new RSVPModelContainer();

        //
        // GET: /Registration/

        public ActionResult ThankYou(RegistrationModel model)
        {
            return View(model);
        }
        
        public ActionResult Login(int? EventID)
        {
            LoginModel model = new LoginModel();
            if (EventID.HasValue)
            {
                Event eventt = db.Events.Find(EventID.Value);
                if (eventt != null)
                {
                    model.EventId = eventt.Id;
                    model.Title = eventt.Title;
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            Event eventt = db.Events.Find(model.EventId);

            if (ModelState.IsValid)
            {
                if ((eventt!=null) && (eventt.Password == model.PasswordLogin))
                {
                    var registrationsByEvent = db.Registrations.Include(r => r.Event).Where(r => r.EventId == model.EventId);
                    ViewBag.EventTitle = eventt.Title;
                    return View("Index", registrationsByEvent.ToList());
                }
                else
                {
                    ViewBag.EventTitle = eventt.Title;                    
                    ModelState.AddModelError("PasswordLogin", "Incorrect password.");
                }
            }

            model.Title = eventt.Title;
            return View(model);
        }

        //
        // GET: /Registration/Create

        public ActionResult Register(int? EventID)
        {
            RegistrationModel model = new RegistrationModel();

            if (EventID.HasValue)
            {
                var eventt = db.Events.Find(EventID.Value);
                model.EventId = EventID.Value;
                model.EventTitle = eventt.Title;
                model.EventCompany = eventt.CompanyName;
                model.EventEmail = eventt.CompanyEmail;
            }
            ViewBag.EventId = new SelectList(db.Events, "Id", "Title");
            return View(model);
        }

        //
        // POST: /Registration/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                Registration registration = new Registration();
                registration.EventId = model.EventId;
                registration.Salutation = model.Salutation;
                registration.FirstName = model.FirstName;
                registration.LastName = model.LastName;
                registration.CompanyName = model.CompanyName;
                registration.CompanySize = "";
                registration.JobTitle = model.JobTitle;
                registration.JobRole = "";
                registration.Email = model.Email;
                registration.Contact = model.Contact;
                registration.HasParking = model.HasParking;
                registration.Agree = model.Agree;

                db.Registrations.Add(registration);
                db.SaveChanges();
                ViewBag.EventId = model.EventId;
                return View("ThankYou", model);
            }

            ViewBag.EventId = model.EventId;
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EventRSVP/Views/Event/Create.cshtml
@model EventRSVP.Models.EventModel

@{
    ViewBag.Title = "Create";
}
<h2></h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Create Event</legend>
        <div class="form-group">
            <label>Event Title</label>

            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.Title)
                @Html.EditorFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            <label>Company</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.CompanyName)
                @Html.EditorFor(model => model.CompanyName)
            </div>

        </div>
        <div class="form-group">
            <label>Company Email</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.CompanyEmail)
                @Html.EditorFor(model => model.CompanyEmail)
            </div>
        </div>
        <div class="form-group">
            <label>Event Password</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.Password)
                @Html.EditorFor(model => model.Password)
            </div>
        </div>
        <p>
            <input type="submit" class="btn btn-default" value="Create" />
        </p>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventRSVP/Views/Event/Edit.cshtml
@model EventRSVP.Event

@{
    ViewBag.Title = "Edit";
}

<h2></h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit Event</legend>

        @Html.HiddenFor(model => model.Id)

      <div class="form-group">
            <label>Event Title</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.Title)
                @Html.EditorFor(model => model.Title)
            </div>
        </div>
        <div class="form-group">
            <label>Company</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.CompanyName)
                @Html.EditorFor(model => model.CompanyName)
            </div>

        </div>
        <div class="form-group">
            <label>Company Email</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.CompanyEmail)
                @Html.EditorFor(model => model.CompanyEmail)
            </div>
        </div>
        <div class="form-group">
            <label>Event Password</label>
            <div style="width: 250px;">
                @Html.ValidationMessageFor(model => model.Password)
                @Html.EditorFor(model => model.Password)
            </div>
        </div>
        <p>
            <input type="submit" class="btn btn-default" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventRSVP/Views/Event/Index.cshtml
@model IEnumerable<EventRSVP.Event>

@{
    ViewBag.Title = "Index";
}

<div class="row">
<h2 class="col-lg-10">Events RSVP</h2>
    <div class="col-lg-2">
        <br />
        <a href="~/Event/Create" class="btn btn-primary">Create</a>
         @Html.ActionLink("Logout", "Logout", new { }, new { @class = "btn btn-default"})
        </div>
</div>

<table class="table table-striped">
    <tr>
        <th>Event Title</th>
        <th>Company Name</th>
        <th>Company Email</th>
        <th>Password</th>
        <th>Registration Link</th>
        <th>Registration List</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>@Html.ActionLink(Url.Action("Register", "Registration", new { EventID = item.Id }), "Register", "Registration",  new { EventID = item.Id }, "")</td>
        <td>@Html.ActionLink("Registration List", "Login", "Registration",  new { EventID = item.Id }, "")</td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { onclick = "return confirm('Do you really want to delete this Event?')" })
        </td>
    </tr>
}

</table>

EventRSVP/Views/Event/Login.cshtml
@model EventRSVP.Models.LoginModel
@{
    ViewBag.Title = "Login";
}
    <div class="form-signin">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <h2 class="text-center">Events RSVP&nbsp;&nbsp;&nbsp;</h2>
        <br />
        <br />
        <div class="form-group">    
                @Html.ValidationMessageFor(model => model.PasswordLogin)   
                @Html.PasswordFor(model => model.PasswordLogin, new {@placeholder = "Password" })
        </div>
    
        <p>
            <input type="submit" class="btn btn-lg btn-primary btn-block" value="Login" />
        </p>
    }
</div>